### ISSUE TITLE
possible incorrect equation

### ISSUE THREAD

**Issue by karl-gardner** [rafaelpadilla/review_object_detection_metrics#106]
Hello Rafael,

I'm wondering if the equation for 11 point interpolation could be wrong. If you think about the sum in the AP formula, wouldn't it be divided by 10 not 11 so wouldn't the correct term before the sum be: 1/(11-1). Because the width of every step in the 11 points is only 0.1 not 0.09 as you currently have. This would affect the final average precision value:

![image](https://user-images.githubusercontent.com/91646805/170778585-50c342fe-16d4-4584-8458-2d1505e706f2.png)

If you divide by 10 instead of 11 you would get 0.975 instead of 0.8864.
Let me know if this makes sense or if I am wrong on this.

Thanks,

Karl Gardner

**Comment by rafaelpadilla** [comment]
Closing this issue as it is being discussed [here](https://github.com/rafaelpadilla/Object-Detection-Metrics/issues/167)
