### ISSUE TITLE
Tool crashes because of metadata files in the annotations folder

### ISSUE THREAD

**Issue by vinod-gutta** [rafaelpadilla/review_object_detection_metrics#11]
**Issue:**
When I provided a folder path which has absolute annotations files (.txt), tool also trying to read metadata file ".DS_Store" (macOS) present in the same folder. This crashing the GUI tool. 

**Suggestion for fixing:** Validate the file extension before accessing/reading.

**Comment by rafaelpadilla** [comment]
@vinod-gutta 

Thank you for your report. 

Yes, you are right, such system files are usually hidden in the folders and were being considered. I have fixed that.

Please, update your repository and let me know if it works now. :)

**Comment by vinod-gutta** [comment]
@rafaelpadilla Thanks for fixing quickly. I tested it and works fine. Closing the issue!
