### ISSUE TITLE
Coordinates format has repeated option

### ISSUE THREAD

**Issue by NIKHILDUGAR** [rafaelpadilla/review_object_detection_metrics#119]
![printshot_main_screen](https://user-images.githubusercontent.com/30868407/223043282-78b44c3b-3cc5-4552-8324-859b3141bd27.png)

Coordinates format 1 and 2 are the same and there should be one that takes the absolute value.

**Comment by rafaelpadilla** [comment]
I disagree. All formats are different.
Some consider x,y,w,h and others consider x,y,x2,y2.
There are options for absolute and relative values as well.

What format do you use that is not covered in one of these options?

**Comment by NIKHILDUGAR** [comment]
There seems to be no textual difference between the first 2 options. I wanted to use x center, ycenter, and width, height on absolute values this is what my UI looks like currently.
![Screenshot from 2023-03-06 16-14-13](https://user-images.githubusercontent.com/30868407/223088430-84a6cf62-2299-47f6-9ef8-46fbb3dab5e3.png)

**Comment by rafaelpadilla** [comment]
If you compare the first two options horizontally, the difference is that one uses <class_id>, while the other requires <class_name>.
If you compare them vertically, one requires ABSOLUTE values, while the other requires RELATIVE ones.

As your format is not fully supported, you will need to adapt your format for one of the supported ones.

**Comment by NIKHILDUGAR** [comment]
ok understood. thank you.
