### ISSUE TITLE
Can you share commands on how to run the coco and PascalVOC evaluators via terminal to generate the outputs?

### ISSUE THREAD

**Issue by NIKHILDUGAR** [rafaelpadilla/review_object_detection_metrics#120]
Thank you.

**Comment by kalikhademi** [comment]
Where did you put the instructions on running through terminal? I tried to use GUI but it did not work for me. Can you share a sample notebook or something like that?

**Comment by kalikhademi** [comment]
> Thank you.

Hi Did you find any instructions?
