### ISSUE TITLE
No results 

### ISSUE THREAD

**Issue by Alioth-1701** [rafaelpadilla/review_object_detection_metrics#121]
I entered the information as the instructions told, but there were no results after running the program. Every value shows as 0, and noting is drawn on the graphs. 

![{P_%@3BIL_XTP~L`U4J(%)F](https://user-images.githubusercontent.com/117868014/233286368-ba06beca-1c32-4d5a-93de-5f2e47247524.png)

The result looks like this:

![_WKUQJCL51E04@3582652QM](https://user-images.githubusercontent.com/117868014/233286534-9acd16dc-cfb0-4295-9fef-84c490891784.png)

The function of "show detections statistics" shows perfectly the bounding boxes. So, I am unsure if it was with my class, which is only one class, or if there are other issues. 
 And I wrote the class file like this:

![Z XI5$H9ZCHX5_JMGLBIZAM](https://user-images.githubusercontent.com/117868014/233286873-4498a98f-b460-415b-97a5-68cc781b590e.png)

Please help me with it. Thank you so much

**Comment by rafaelpadilla** [comment]
Could you please share some of your images, detection and ground-truth files?

**Comment by kalikhademi** [comment]
I tried the evaluators in the script and it shows zero for all metrics too. 

`groundtruth_bbs =coco2bb(annotation.json, bb_type=BBType.GROUND_TRUTH)
  detected_bbs = coco2bb(detection.json, bb_type=BBType.DETECTED)
  result = get_coco_summary(groundtruth_bbs,detected_bbs)`

I appreciate it if you could let me know what the problem might be!

Thanks,

**Comment by rafaelpadilla** [comment]
@kalikhademi 
Could you please share some of your images, detection and ground-truth files?
