### ISSUE TITLE
Feature request: Docker containerization

### ISSUE THREAD

**Issue by sezan92** [rafaelpadilla/review_object_detection_metrics#122]
## Objective

This issue is to discuss the dockerization of this project.

hello @rafaelpadilla i liked this project a lot as it has made object detection evaluation a lot easier. i was thinking about dockerizing the project. If none has tried yet. can I contribute on dockerization ?

**Comment by rafaelpadilla** [comment]
Hi @sezan92 ,

Thank you for your message.

Amazing! Sure, that would be an excellent contribution. 

Please, open a PR with your contributions.

**Comment by sezan92** [comment]
hello, I am actually working on it in https://github.com/sezan92/review_object_detection_metrics/pull/1 , but the issue is closed. sorry for that. can I reopen?
