### ISSUE TITLE
move(self, int, int): argument 1 has unexpected type 'float'

### ISSUE THREAD

**Issue by MathewsJosh** [rafaelpadilla/review_object_detection_metrics#123]
Hello, i am currently having this problem, what am i doing wrong?

>>python run.py

Traceback (most recent call last):
  File "C:\Users\teued\Downloads\review_object_detection_metrics-main\run.py", line 13, in <module>
    ui = Main_Dialog()
  File "C:\Users\teued\Downloads\review_object_detection_metrics-main\src\ui\run_ui.py", line 37, in __init__
    self.center_screen()
  File "C:\Users\teued\Downloads\review_object_detection_metrics-main\src\ui\run_ui.py", line 44, in center_screen
    self.move(left, top)
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'float'
  move(self, int, int): argument 1 has unexpected type 'float'

**Comment by rafaelpadilla** [comment]
Oi Mathews,

Você instalou os pacotes com conda, pip?
Me parece que a versão do QT que você está usando pede coordenadas em `int` e a versão do QT que estamos usando pode receber em `float`.

Faz o seguinte:
1. Cria um ambiente do zero.
2. Instala os pacotes: [requirements.txt](https://github.com/rafaelpadilla/review_object_detection_metrics/files/11366788/requirements.txt)
3.  `sudo apt-get install libxcb-xinerama0` como recomendado [aqui](https://github.com/NVlabs/instant-ngp/discussions/300#discussioncomment-3985753)

**Comment by MathewsJosh** [comment]
Fala Rafael, tudo bom?

Havia seguido as instruções do seu readme e agora refiz os passos como você indicou (com exceção do último por estar no windows), mesmo assim o problema persiste. 
Existe alguma alternativa para o comando `sudo apt-get install libxcb-xinerama0` no Windows?

**Comment by rafaelpadilla** [comment]
Não sei qual seria o pacote compatível no Windows.

Se você for no fonte do projeto e trocar em 2 partes do código:
`self.move(left, top)` para `self.move(int(left), int(top))`, pode ser que resolva.

Este problema me parece estar relacionado com a versão do pyqt5 (que conflita com ora com o matplotlib, ora com o cv2). 

Dá uma olhada [aqui](https://github.com/NVlabs/instant-ngp/discussions/300) e [aqui](https://askubuntu.com/questions/1298645/shared-library-not-found-for-pyqt5-libxcb-xinerama-so-0-not-found) . Talvez ajude.

Quando eu conseguir um tempo, vou gerar um `requirements.txt` com todo o pacote necessário

**Comment by MathewsJosh** [comment]
Boaaaa Rafael, substituí todas as aparições do self.move(left, top) para self.move(int(left), int(top)) e resolveu! Obrigado!

Outro erro surgiu aqui quando cliquei no botão "plot bounding boxes per class" na parte de análise dos ground truths `AttributeError: 'FigureCanvasQTAgg' object has no attribute 'set_window_title'. Did you mean: 'setWindowTitle'?` Resolvi também substituindo todos os `fig.canvas.set_window_title` por `fig.canvas.setWindowTitle`.

**Comment by rafaelpadilla** [comment]
Excelente notícia, Mathews! 

Em breve, com mais tempo, irei gerar um `requirements.txt` com as versões atualizadas e não teremos mais este erro.

Vou fechar este issue. Caso, necessite, por favor, crie um outro ou reabra este.
