### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by Sayali22** [rafaelpadilla/review_object_detection_metrics#124]
```
python run.py
Error: run.py", line 7, in <module>
    from src.ui.run_ui import Main_Dialog
ModuleNotFoundError: No module named 'src'
```
How to resolve this?
I am using the Anaconda prompt on Windows.

**Comment by rafaelpadilla** [comment]
Did you run he command `python setup.py install` ?

**Comment by Sayali22** [comment]
Yes.
I have used below commands before running python run.py
```
conda env create -n metrics --file environment.yml
conda activate metrics
python setup.py install

```

**Comment by hahv** [comment]
I encountered such the same issue. The `src` installed package seems to be easy to conflict with the other packages/projects.
 My suggestion is to rename the main folder `src` to serve as a unique name for installing the package @rafaelpadilla.

**Comment by Sayali22** [comment]
Thank you so much @hahv Renaming to src worked.
