### ISSUE TITLE
Error when validating absolute coordinates

### ISSUE THREAD

**Issue by sopherrmann** [rafaelpadilla/review_object_detection_metrics#13]
Hi Devs!

I think there is an issue when validating that coordinates are absolute. Currently when having absolute but not integer coordinates the validation fails.

The issue seems to happen [here](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/utils/validations.py#L482). Coordinates are checked to be integers instead of absolute values. Changing `int` to `abs` should fix this.

**Comment by rafaelpadilla** [comment]
Hi @sopherrmann ,

Thank you for reporting that. Could you please, provide an example of your detections and ground-truth coordinates, that make the problem?

**Comment by rafaelpadilla** [comment]
@sopherrmann 

That is not an issue. This is done to validate if the user is informing coordinates in integer values.

Ex: It checks if the user is passing the absolute coordinate x in the format `123.45` instead of `123.0` or `123`.

The code could be changed to convert it to integer automatically, but I believe this should be done by the user. What do you think?

**Comment by sopherrmann** [comment]
Hi @rafaelpadilla

The problem occurred when loading most of my detections 
format `<class_name> <confidence> <left> <top> <right> <bottom> (ABSOLUTE)`

Loading e.g. the following detection fails:
`chair 0.8258069157600403 220.60165405273438 5.041046619415283 391.4727478027344 203.5130615234375`
because `float(391.4727478027344) == int(float(391.4727478027344))` equal `False`

while e.g. this one succeeds
`table 0.9834269285202026 190.3743896484375 14.700692176818848 896.0 489.2214050292969`
because `float(896.0) == int(float(896.0))` equals `True`

[Here](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/utils/validations.py#L478) `blocks_abs_values` is set to [4] for in my case (as defined [here](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/utils/converter.py#L250)). Therefore always only the 4th element per detection is considered (as shown above). For what I understand maybe it also makes more sense to check all last 4 elements (?)

So I'm afraid this somehow is an issue with my dataset. Am I missing something or are my detections just somehow wrongly formatted?
