### ISSUE TITLE
numpy: set_window_title moved to manager

### ISSUE THREAD

**Issue by jdede** [rafaelpadilla/review_object_detection_metrics#134]
set_window_title moved from fig.canvas to fig.canvas.manager.
-> https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.4.0.html

**Comment by rafaelpadilla** [comment]
Hi @jdede 

thank you for opening this issue. 

can you please describe if the existing library is raising an exception or this is a nice to have for a higher matplot lib version?

**Comment by jdede** [comment]
The currently used Python version according to [environment.yml](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/environment.yml) is 3.9 (released Oct. 5, 2020) and even in the current Debian stable, Python 3.11 is included.

The API-change in matplotlib 3.4.0 is from 2021. Right now, 3.8 is released. In Debian stable, matplotlib 3.6 is available. I think it makes sense to react to those changes and change everything to the current versions of the used libraries.

Maybe, it also makes sense to update the environment.yml to have everything in a consistent state. Otherwise, updating and fixing those tiny, little API-changes will get more and more complex.

Regarding your question: In the current environmet.yml, no matplotlib version is given. I am not that familiar with conda: Which version is used in this case? The most recent one or will conda automatically select a suitable one which works with the other libraries? Maybe this is also one reason with the failing build as mentioned in #137 ?
