### ISSUE TITLE
Result is 0

### ISSUE THREAD

**Issue by moritz-e** [rafaelpadilla/review_object_detection_metrics#138]
Hello,
first of all, thankyou for publishing such a usefull tool. this is exacly what is was looking for.

my problem: i get a result of 0 with every metric.
i am predicting small objects so only AP small should get results.

I am using Pascal voc for ground truth and class name confidence left top width height absolut for the detections.

![image](https://github.com/rafaelpadilla/review_object_detection_metrics/assets/60695156/eb9c70c7-cb5a-4ac7-b63b-862629b53bfa)

![image](https://github.com/rafaelpadilla/review_object_detection_metrics/assets/60695156/8bad3798-8c1b-4923-ae17-95e7a04cd19d)

AP: 0.0
AP50: 0.0
AP75: 0.0
APsmall: 0.0
APmedium: nan
APlarge: nan
AR1: 0.0
AR10: 0.0
AR100: 0.0
ARsmall: 0.0
ARmedium: nan
ARlarge: nan

what can i do to fix it?

I know the accuracy is not very good. but at least not 0, right?

**Comment by rafaelpadilla** [comment]
Hi @moritz-e 
Looking at the detections in your sample, it seems that you have (at least in that particular sample) lots of bad detections and missed groundtruths.

You have 135k images. Could you please try the following:

Select ~5 images and run your results for those. See if your results change.

Let me know what your results are.

**Comment by moritz-e** [comment]
Hi @rafaelpadilla ,
thanks for the reply and the instructions.
It was my fault. maybe you can implement this also in a further version:

i had only one class: mite
so i asumed that the programm will map it 1:1
but in my predictions because of transformation i had the class 'mite' with ' '
i didnt noticed it and didnt recognised it. so maybe remove " " or ' ' from class name or ignore it when matching to the ground truth.

cheers

**Comment by rafaelpadilla** [comment]
Hi @moritz-e 

I'm glad you found the solution. :) 

Maybe modifying the classes (e.g. removing special characters) might not be a good solution, because there might be cases that these characters are there to actually represent a different class. Maybe in the future, if other requests like those appear, we may consider it.
