### ISSUE TITLE
self.move incorrect work

### ISSUE THREAD

**Issue by p0v4r** [rafaelpadilla/review_object_detection_metrics#146]
Cannot start an app due to:
```
TypeError: arguments did not match any overloaded call:
  move(self, a0: QPoint): argument 1 has unexpected type 'float'
  move(self, ax: int, ay: int): argument 1 has unexpected type 'float'
```
That is happening 'cause of function move cannot work with floats, quickfix in PR submitted.

**Comment by p0v4r** [comment]
@rafaelpadilla 
I have no permission for PR, so quickfix here:
run_ui.py, 44:9
`self.move(int(left), int(top))`
splash.py, 19:9
`self.move(int(left), int(top))`

**Comment by Spectralimaging** [comment]
Warning: It was not possible to find the resolution of image 1.txt
