### ISSUE TITLE
Metrics for oriented/rotated bounding boxes

### ISSUE THREAD

**Issue by Petros626** [rafaelpadilla/review_object_detection_metrics#148]
Hey,

I would like to know, if this tool supports not only axis aligned bounding boxes for the evaluation. Is it planned in the future to implement this feature?

Thanks in advance

**Comment by rafaelpadilla** [comment]
It does not support oriented (rotated) bounding box. If you need to evaluate your detections in sick datasets, such as DOTA and UCAS, you need to adapt our code. 
I believe you just need to modify the IOU part.
If you want to collaborate, please open a PR and tag me as a reviewer. 🙏
