### ISSUE TITLE
Question about precision x curve calculation

### ISSUE THREAD

**Issue by luizwritescode** [rafaelpadilla/review_object_detection_metrics#151]
During my research I've found the Precision x Recall curve can be calculated two different ways. After matching predictions with ground truth boxes based on a IoU threshold, whenever possible, and ranking all predictions by confidence score, you must...

1. (this paper) For each prediction, calculate cumulative precision and recall. This means each prediction generates a point in the PR curve for a specific confidence threshold.

2. Set a confidence threshold of 0 and only look at predictions with confidence score equal to or higher than confidence threshold. Calculate precision and recall. That's one point in the PR Curve. Keep increasing the threshold until you have enough points in PR curve. This means each confidence threshold generates a point in the PR curve.

I understand both methods are correct, but are analyzing different things. Which of the two methods is the one used to calculate AP and mAP?

**Comment by rafaelpadilla** [comment]
The second approach considers each prediction’s impact on cumulative precision and recall, providing a comprehensive view of the model’s performance across all confidence levels. It is the standard method used in evaluation protocols like PASCAL VOC and MS COCO, and it’s the one described in our paper.

Method 2 seems to be more commonly associated with binary classification tasks and is less suited for calculating AP and mAP in object detection.

**Comment by rafaelpadilla** [comment]
I believe the question was answered. :+1: 
So, I am closing this issue. Please, reopen it if you think it is needed. :pray:
