### ISSUE TITLE
Error when trying to run metrics on ground truth

### ISSUE THREAD

**Issue by matt-sharp** [rafaelpadilla/review_object_detection_metrics#18]
I've managed to successfully display the ground truth statistics but when I try to run the metrics I receive the following error:

![image](https://user-images.githubusercontent.com/13571774/109159073-19536080-776c-11eb-8391-00fdd35068d4.png)

My files containing the classes looks like this:

[hrsc2016_class_lev2.txt](https://github.com/rafaelpadilla/review_object_detection_metrics/files/6043205/hrsc2016_class_lev2.txt)

I'm using YOLO annotation and trying to run this on my training set.

**Comment by rafaelpadilla** [comment]
Hi @matt-sharp ,

In order to see what is happening, please, send me at least 1 detection .txt file, its respective ground .txt file and image.

Best regards,
Rafael

**Comment by matt-sharp** [comment]
@rafaelpadilla I have solved the error - I was missing the confidence value in my detection annotation file.  What confused me initially was the error message.  This led me to believe the issue was with my file containing the list of classes.
