### ISSUE TITLE
Absolute Values Ground Truth

### ISSUE THREAD

**Issue by sgalea87** [rafaelpadilla/review_object_detection_metrics#20]
The default format for ground truth absolute values is XYWH (ret = converter.text2bb(self.dir_annotations_gt, bb_type=BBType.GROUND_TRUTH)).

Since this is not documented anywhere I had to look at the code to try and find why my GT bounding boxes were not matching. 

Ideally there should be two format options for Absolute Values, XYWH and XYX2Y2.

**Comment by rafaelpadilla** [comment]
@sgalea87 ,

Thank you for your message. You are right, the visual interface does not inform about the default format for the GT absolute bounding boxes. Your suggestion is very welcome. I will include the XYX2Y option.

By the way, what dataset are you using that provides annotations in text file with the XYX2Y2 bounding box format?

**Comment by sgalea87** [comment]
Thank you for the quick reply.

This is the dataset I am using https://bdd-data.berkeley.edu/.

This is a great tool btw and has saved me a lot of time in my research papers as well as my dissertation.

**Comment by rafaelpadilla** [comment]
@sgalea87 ,

Good to know that our tool has saved you some time. :)

The tool is not saving the recall vs precisions points, but it generates these points in a pandas object that you could use.

Then you can produce a table similar to [this one](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/data/images/table_1_toyexample.png). In [this](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/evaluators/pascal_voc_evaluator.py#L81) function, set the argument `generate_table` to `True` and  the function will return the pandas object.

Hope it helps.
Rafael

**Comment by rafaelpadilla** [comment]
Closing... as there is no answer on this topic.
