### ISSUE TITLE
Unable to resize image viewer window

### ISSUE THREAD

**Issue by matt-sharp** [rafaelpadilla/review_object_detection_metrics#21]
Once the ground-truth or detection statistics viewer is displayed I'm unable to resize it either by maximizing or dragging with the cursor.  The image window is quite small which makes things difficult to see when objects, bounding boxes and labels are small or clustered together.
Please would it be possible to add the capability to resize this window and collapse the statistics box?

**Comment by rafaelpadilla** [comment]
@matt-sharp ,

Thanks again for your feedback.

It would be good if the user could resize the window to have a better visualization of the image. I will put this feature into our list of improvements.

By then, if you choose to save the image, it will be saved in its original resolution, so you can see it better.

Best regards,
Rafael

**Comment by rafaelpadilla** [comment]
Closing as there is no interaction
