### ISSUE TITLE
Error: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by 5a7man** [rafaelpadilla/review_object_detection_metrics#26]
Getting this error when prediction.json is used in detection section
![Capture](https://user-images.githubusercontent.com/58083322/110396290-9696a380-8091-11eb-8e03-6afc59c54958.PNG)

predication.json file format
![Capture2](https://user-images.githubusercontent.com/58083322/110396691-45d37a80-8092-11eb-83f2-0d2b51708a4f.PNG)

**Comment by rafaelpadilla** [comment]
Hi @5a7man,

Your json file does not follow COCO format. 

Please, find [here](https://github.com/rafaelpadilla/review_object_detection_metrics/tree/main/data/database/dets/coco_format) a sample of json files supported for coco that can be used to report your detections.
