### ISSUE TITLE
Output a PR curve image with all classes

### ISSUE THREAD

**Issue by eduramiba** [rafaelpadilla/review_object_detection_metrics#29]
Hi,

Would it be possible to also plot a PR curve with all classes in it?

Thanks,
Eduardo

**Comment by rafaelpadilla** [comment]
Hi @eduramiba ,

Good idea! 

I have added this functionality. Please, update your repository. Now, in the output folder, a plot named `all_classes.png` is created. Let me know if it works for you.

**Comment by eduramiba** [comment]
Thank you that's great!
