### ISSUE TITLE
Detection statistics window crashes - possible cause = adding annotation containing FP?

### ISSUE THREAD

**Issue by matt-sharp** [rafaelpadilla/review_object_detection_metrics#30]
I can successfully generate 1 detection box for 1 image but when I try to add another image to my detections folder which contains 2 detections in the image the GUI crashes and closes.
Is it because of the FP picked up in the 2nd image?

Here are my images:
![100000003](https://user-images.githubusercontent.com/13571774/110662018-06557d00-81bd-11eb-8e9a-a919ccea8968.jpg)
![100000005](https://user-images.githubusercontent.com/13571774/110662024-06ee1380-81bd-11eb-8d93-df6286187925.jpg)

ground truth:
[100000003.txt](https://github.com/rafaelpadilla/review_object_detection_metrics/files/6117366/100000003.txt)
[100000005.txt](https://github.com/rafaelpadilla/review_object_detection_metrics/files/6117367/100000005.txt)
(2nd image has 1 labelled object)
detections:
[100000003.txt](https://github.com/rafaelpadilla/review_object_detection_metrics/files/6117369/100000003.txt)
[100000005.txt](https://github.com/rafaelpadilla/review_object_detection_metrics/files/6117370/100000005.txt)
(2nd image has 2 detections, one with very low confidence.)

class names:
[hrsc2016_class_lev2.txt](https://github.com/rafaelpadilla/review_object_detection_metrics/files/6117375/hrsc2016_class_lev2.txt)

**Comment by rafaelpadilla** [comment]
@matt-sharp ,

No. FP should not be a problem at all.

With the files you provided me, it is working nicely:

![result_100000005](https://user-images.githubusercontent.com/31217453/110679462-42391400-81b6-11eb-946d-4dd857e56416.jpg)

And the results are:
![image](https://user-images.githubusercontent.com/31217453/110679277-0c942b00-81b6-11eb-9705-cf67d3178cd1.png)

*Maybe the name of the image does not correspond to the annotation files you provided.*

I zipped everything with the requested structure. Please, update your code and try with the files below.
[issue_30.zip](https://github.com/rafaelpadilla/review_object_detection_metrics/files/6118102/issue_30.zip)

**Comment by matt-sharp** [comment]
@rafaelpadilla I'm now able to successfully run the GUI with a different set of data.  I'm not entirely sure what the issue was here but possibly it occurs when switching between different image and annotation paths multiple times in one session window?
Anyway, this is now resolved so I'll close and thanks for your help!
