### ISSUE TITLE
Add F1-score to results output window

### ISSUE THREAD

**Issue by matt-sharp** [rafaelpadilla/review_object_detection_metrics#32]
I've managed to calculate the F1-score here:
[https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/evaluators/pascal_voc_evaluator.py](url)

But I'm having difficulty in understanding how this metric can be added to the results output window.
Please can you give some guidance on which parts of the code need to be edited? thanks!

**Comment by rafaelpadilla** [comment]
@matt-sharp 

Check [here](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/ui/run_ui.py#L394). You have add the metrics into one of the dictionaries `coco_res` or `pascal_res` before calling the function `show_dialog`.

Example:
`pascal_res['F1-score'] = your_value_goes_here`

Please, consider closing this issue if your question was answered accordingly

**Comment by matt-sharp** [comment]
@rafaelpadilla I've added the F1-score to my results window.  I had to change the code in a few different places to ensure the additional metric could be selected for display.  
For anyone else interested here's the code I used:

https://github.com/matt-sharp/review_object_detection_metrics/blob/faf77cf7b1f6b1ce82b0aea6c22d76fa2b4d75f9/src/evaluators/pascal_voc_evaluator.py#L226-L233

https://github.com/matt-sharp/review_object_detection_metrics/blob/faf77cf7b1f6b1ce82b0aea6c22d76fa2b4d75f9/src/ui/main_ui.py#L240-L243

https://github.com/matt-sharp/review_object_detection_metrics/blob/faf77cf7b1f6b1ce82b0aea6c22d76fa2b4d75f9/src/ui/main_ui.py#L548

https://github.com/matt-sharp/review_object_detection_metrics/blob/faf77cf7b1f6b1ce82b0aea6c22d76fa2b4d75f9/src/ui/main_ui_tabs.py#L110-L113

https://github.com/matt-sharp/review_object_detection_metrics/blob/faf77cf7b1f6b1ce82b0aea6c22d76fa2b4d75f9/src/ui/main_ui_tabs.py#L527

https://github.com/matt-sharp/review_object_detection_metrics/blob/faf77cf7b1f6b1ce82b0aea6c22d76fa2b4d75f9/src/ui/results.py#L34-L37

https://github.com/matt-sharp/review_object_detection_metrics/blob/faf77cf7b1f6b1ce82b0aea6c22d76fa2b4d75f9/src/ui/run_ui.py#L363-L379
