### ISSUE TITLE
[Bug] Coordinates for XYWH and XYX2Y2 swaped when type_coordinates == CoordinatesType.RELATIVE

### ISSUE THREAD

**Issue by dmesquita** [rafaelpadilla/review_object_detection_metrics#33]
Hi, thanks for the tool!

I think the condition to set the coordinates for relative bounding boxes are swaped:

```python
from src.bounding_box import BoundingBox

# a GT bbox with relative coordinates in the XYWH format
bbox = BoundingBox(
    "img_filename",
    "category_class",
    (
        0.04287003610108303,
        0.04801829268292683,
        0.22021660649819497,
        0.11178861788617887,
    ),
    CoordinatesType.RELATIVE,
    (540, 960),
    None,
    BBType.GROUND_TRUTH,
    BBFormat.XYWH,
)

print(bbox)

>>> image name: img_filename
class: category_class
bb (XYWH): (-36.0, -8.0, 119.0, 108.0)
bb (X1Y1X2Y2): (-36.0, -8.0, 83.0, 100.0)
area: 13080.0
bb_type: None

```

If I change it to the XYX2Y2 format:

```python
# a GT bbox with relative coordinates in the XYWH format
bbox = BoundingBox(
    "img_filename",
    "category_class",
    (
        0.04287003610108303,
        0.04801829268292683,
        0.22021660649819497,
        0.11178861788617887,
    ),
    CoordinatesType.RELATIVE,
    (540, 960),
    None,
    BBType.GROUND_TRUTH,
    BBFormat.XYX2Y2,
)

print(bbox)

>>> image name: img_filename
class: category_class
bb (XYWH): (23.0, 46.0, 96.0, 61.0)
bb (X1Y1X2Y2): (23.0, 46.0, 119.0, 107.0)
area: 6014.0
bb_type: None

```

**Comment by rafaelpadilla** [comment]
Hi @dmesquita ,

Thank you for your message.

The values are correct. Please, see the explanation below:

When you create the following bounding box:

`bbox = BoundingBox(
    "img_filename",
    "category_class",
    (
        0.04287003610108303,
        0.04801829268292683,
        0.22021660649819497,
        0.11178861788617887,
    ),
    CoordinatesType.RELATIVE,
    (540, 960),
    None,
    BBType.GROUND_TRUTH,
    BBFormat.XYWH,
)`

1) you are setting the following bounding box coordinates in the **relative** format:
`x_center = 0.04287003610108303
y_center = 0.04801829268292683
width = 0.22021660649819497
height = 0.11178861788617887`

2) you are considering the resolution of your image as `width=540` and `height=960`

Note that the relative coordinates you are providing are in the following format `(x_center, y_center, width, height)`:
![image](https://user-images.githubusercontent.com/31217453/111238876-c9332580-85d6-11eb-975d-4303b551de40.png)

So, when you convert the relative coordinates into **absolute** coordinates, you will have the following values:
X = -36.3086
Y = -7.9024
width = 118.9169
height = 107.3170

Best regards,
Rafael

**Comment by dmesquita** [comment]
Thanks! It' seems strange, I'm using a dataset from the [Azure Custom Vision export](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-labeled-dataset#coco) and it says the coordinates are `"bbox": [x,y,width,height]"`. When I plot them using x and y with [bbox](https://github.com/varunagrawal/bbox) (instead of Xc and Yc) the bb seem to be ploted correctly. I'll dig deep to see what's going on, thanks!

**Comment by rafaelpadilla** [comment]
@dmesquita ,

Note that [Azure](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-labeled-dataset#coco) follows COCO's annotation format, which is `x_relative, y_relative, width_relative, height_relative`.

In our repository, the BoundingBox object in the format XYWH RELATIVE refers to YOLO's relative format:
![image](https://user-images.githubusercontent.com/31217453/111240612-588e0800-85da-11eb-8c08-a3d6db5142d8.png)

The difference is that YOLO's format has the first two coordinates (x,y) as the center of the bounding box.

I hope that helped. :)
