### ISSUE TITLE
OKS metric support

### ISSUE THREAD

**Issue by ssbagalkar** [rafaelpadilla/review_object_detection_metrics#35]
Is there a possibility to add OKS metrics to this? I can write the code and submit a PR is that's acceptable

**Comment by thadeuluiz** [comment]
Hello, @ssbagalkar.

Currently, we only provide metrics for bounding-box based metrics, as we use an unified bbox class to abstract all the possible formats and then do the metric computations in an agnostic manner.

Of course, kp functionality to this project would be a welcomed addition. If possible, we would prefer a similar scheme to what is currently available, that is, a parser/class for keypoints and then the functions that calculate the metrics using that unified interface.

That said, I have a couple questions.

1. What are the most relevant formats used in kp datasets? Is it feasible to unify said formats in similar fashion to what we for boxes?
2. Using the agreed format, what metrics would we be able to support?

**Comment by rafaelpadilla** [comment]
Closing issue as there is no comments lately
