### ISSUE TITLE
I met an Error when I use anaconda to create the environment.

### ISSUE THREAD

**Issue by HsLOL** [rafaelpadilla/review_object_detection_metrics#36]
hi, @rafaelpadilla 

After I ran this command 
conda env create -n env_name --file environment.yml 

An Error occured, like this

![image](https://user-images.githubusercontent.com/53011009/112606089-f1cae300-8e52-11eb-9ffa-3ef0036eda2b.png)

how can i solve this problem?

Thanks a lot.

**Comment by rafaelpadilla** [comment]
@HsLOL ,

It seems you do not have python 3.9 installed.

Please, remove the version of the python package in your `environment.yml` (replace the line "  - python=3.9" by "  - python"). And try running the command `conda env create -n env_name --file environment.yml` again.

I'm not sure if that will work, please let me know if that helped.

**Comment by HsLOL** [comment]
> @HsLOL ,
> 
> It seems you do not have python 3.9 installed.
> 
> Please, remove the version of the python package in your `environment.yml` (replace the line " - python=3.9" by " - python"). And try running the command `conda env create -n env_name --file environment.yml` again.
> 
> I'm not sure if that will work, please let me know if that helped.

it doesn't work

I think the environment.yml might be corrected like this 
![image](https://user-images.githubusercontent.com/53011009/112706360-a0683580-8ede-11eb-85ca-5633888a1919.png)

And i got the similar error like this
![image](https://user-images.githubusercontent.com/53011009/112706376-b970e680-8ede-11eb-9c42-b903871b9334.png)

do you have any other advice? Thanks!

**Comment by rafaelpadilla** [comment]
Hi @HsLOL ,

I would try creating a new (empty) conda environment with python 3.9. Then update it with the .yml file.

Take a look at these links:
https://salishsea-meopar-docs.readthedocs.io/en/latest/work_env/python3_conda_environment.html

https://stackoverflow.com/questions/63216201/how-to-install-python3-9-with-conda

**Comment by HsLOL** [comment]
> Hi @HsLOL ,
> 
> I would try creating a new (empty) conda environment with python 3.9. Then update it with the .yml file.
> 
> Take a look at these links:
> https://salishsea-meopar-docs.readthedocs.io/en/latest/work_env/python3_conda_environment.html
> 
> https://stackoverflow.com/questions/63216201/how-to-install-python3-9-with-conda

> I would try creating a new (empty) conda environment with python 3.9. Then update it with the .yml file.

according to your advice, if I could try this way?
- First, 
conda create -n py39 python=3.9

- Second, 
conda activate py39

-Third
delete the line " - python=3.9" in the environment.yml

- Forth
conda env update --file environment.yml

**Comment by rafaelpadilla** [comment]
I am not a conda expert, but it makes sense to me. Have you got it working?

**Comment by HsLOL** [comment]
> I am not a conda expert, but it makes sense to me. Did you get it working?

Yes, it works!

Thanks for your help!
