### ISSUE TITLE
Plotting results with fixed Y- and X-axis values

### ISSUE THREAD

**Issue by NilsBusch98** [rafaelpadilla/review_object_detection_metrics#39]
Hi,
is there any way to make the plots axis limited to a fixed value? (e.g. always show axis from 0 to 1)
This would make comparing different results with each other easier.  
Thanks for any help in advance.

**Comment by rafaelpadilla** [comment]
Hi @NilsBusch98,

Please, take a look at [xlim](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.xlim.html) and [ylim](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.ylim.html). 

You will have to add something like `plt.xlim([0,1])` and `plt.ylim([0,1]) ` after [this line](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/evaluators/pascal_voc_evaluator.py#L261).

I hope it helps.

**Comment by NilsBusch98** [comment]
@rafaelpadilla thx for your quick answer. 
I added xlim and ylim at the location you suggested but it didn't change the way the graph is being plotted. 
Do you have any idea how to fix it? Do I have to add x and ylim at a another location maybe?

**Comment by rafaelpadilla** [comment]
@NilsBusch98 ,

Have you figure your solution out?

**Comment by NilsBusch98** [comment]
@rafaelpadilla unfortunatly i could not figure out any solution yet.

**Comment by rafaelpadilla** [comment]
@NilsBusch98 ,

I have just made these modifications to attend you. I defined the X and Y ranges to be [-0.1, 1.1] as in the image below.

![image](https://user-images.githubusercontent.com/31217453/116266672-136d0200-a752-11eb-825c-1a53c791f5d4.png)

Please, update your code with the latest version to be able to use this modifications. 

If this solves your problem, please, consider closing this issue.

Best regards,
Rafael

**Comment by NilsBusch98** [comment]
The issue is fixed, thank you very much for your help @rafaelpadilla

**Comment by NilsBusch98** [comment]
The issue is fixed, thank you very much for your help @rafaelpadilla
