### ISSUE TITLE
COCO results format not accepted

### ISSUE THREAD

**Issue by pratikkulkarni228** [rafaelpadilla/review_object_detection_metrics#4]
The results format as specified by COCO cannot be parsed.
[{
"image_id": int, "category_id": int, "bbox": [x,y,width,height], "score": float,
}]

Throws error:
(vendor-eval) C:\Vendor evaluation2\review_object_detection_metrics>python run.py
Traceback (most recent call last):
  File "C:\Vendor evaluation2\review_object_detection_metrics\src\ui\run_ui.py", line 258, in btn_statistics_det_clicked
    det_annotations, passed = self.load_annotations_det()
  File "C:\Vendor evaluation2\review_object_detection_metrics\src\ui\run_ui.py", line 115, in load_annotations_det
    ret = converter.coco2bb(self.dir_dets, bb_type=BBType.DETECTED)
  File "C:\Vendor evaluation2\review_object_detection_metrics\src\utils\converter.py", line 31, in coco2bb
    if not validations.is_coco_format(file_path):
  File "C:\Vendor evaluation2\review_object_detection_metrics\src\utils\validations.py", line 302, in is_coco_format
    return is_json(file_path) and json_contains_tags(file_path, [
  File "C:\Vendor evaluation2\review_object_detection_metrics\src\utils\validations.py", line 115, in json_contains_tags
    for key, item in json_object.items():
AttributeError: 'list' object has no attribute 'items'

**Comment by rafaelpadilla** [comment]
Hi @pratikkulkarni228 ,

Please, find in the links below an example of the COCO formats.

[- groundtruth samples](https://github.com/rafaelpadilla/review_object_detection_metrics/tree/main/tests/test_coco_eval/gts)
[- detections samples](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/tests/test_coco_eval/dets)

Please, let me know if you got it working.

**Comment by pratikkulkarni228** [comment]
@rafaelpadilla , Thank you for redirecting me to the sample detections. I got my detections in similar format and it worked.
Closing the issue now.

Thank you

**Comment by fei-pan** [comment]
Hi @rafaelpadilla,

I notice the same issue. So is there a quick way to "convert" or "transform" the COCO instance segmentation results json to the COCO annotation format?

Thank you,
Best regards,

Fei

> Hi @pratikkulkarni228 ,
> 
> Please, find in the links below examples of the COCO formats.
> 
> [- groundtruth samples](https://github.com/rafaelpadilla/review_object_detection_metrics/tree/main/tests/test_coco_eval/gts) [- detections samples](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/tests/test_coco_eval/dets)
> 
> Please, let me know if you got it working.
