### ISSUE TITLE
Detections format <class name> <confidence> <left><top><right><bottom> pruducing error

### ISSUE THREAD

**Issue by matthieu-as** [rafaelpadilla/review_object_detection_metrics#40]
If I choose class name confidence left top right bottom (ABSOLUTE) pruducing error as coordinates format for Detections and I want to show the detection statistics, I always get the UI error: "No file was found for the seleted detection format in the annotations directory" and python warning: "Image not found in the directory None. It is required to get its dimensions"

Does anyone know how to fix this issue?

**Comment by matthieu-as** [comment]
I forgot that the origin of images is at the top left and not the bottom left. Therefore, I confused ymax and ymin of the bounding box and consequently my bottom and top were mixed up. Top corresponds to ymin and bottom to ymax of a bounding box. With this change everything works fine.

**Comment by zaradamou** [comment]
Hi, I am actually also having this issue but have not been able to resolve it. I have xmin,ymin, xmax,ymax to represent left, top,right bottom, but I am still receiving the error you received as well. 

This is an example of what is in the txt file: 

Complete 99.73 81.0693588256836 419.2168273925781 155.7943572998047 706.3161010742188

Any insight is greatly appreciated!
