### ISSUE TITLE
Single Image Metrics

### ISSUE THREAD

**Issue by joeization** [rafaelpadilla/review_object_detection_metrics#41]
Is there any way to produce metrics of each image separately?
Or I should split gt/det here?
https://github.com/rafaelpadilla/review_object_detection_metrics/blob/e32521be14e9c2372bda204c1e30648188c71b21/src/ui/run_ui.py#L336

**Comment by rafaelpadilla** [comment]
Hi @joeization,

@joeization ,

You could split gt and dets the way you mentioned, or you could use the function [get_pascalvoc_metrics](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/e32521be14e9c2372bda204c1e30648188c71b21/src/ui/run_ui.py#L365), passing the argument `generate_table=True`. 

Then you will get a pandas object and obtain a similar table like [this one](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/data/images/table_1_toyexample.png), and get the metrics from there.

I hope that helps.

**Comment by joeization** [comment]
Thanks for your reply
