### ISSUE TITLE
Why it showing me?

### ISSUE THREAD

**Issue by BiponDas2** [rafaelpadilla/review_object_detection_metrics#42]
![Screenshot_10](https://user-images.githubusercontent.com/79183231/116204589-bc215e80-a75e-11eb-86d7-48bde0a595fe.jpg)

The coordinates format is ok but why it showing?
![image](https://user-images.githubusercontent.com/79183231/116204786-ea06a300-a75e-11eb-9040-78b891b185d2.png)

**Comment by rafaelpadilla** [comment]
Hi @BiponDas2,

Note that your file does not follow the format
`<class_id> <confidence> <x_center> <y_center> <width> <height> (RELATIVE)`

Your format might be:
`<class_name> <confidence> <x_center> <y_center> <width> <height> (RELATIVE)`

**Comment by rafaelpadilla** [comment]
Hi @BiponDas2 ,

The problem was that your detection files ended with an extra space (' ').

Update the code. I have removed all leading and trailing whitespaces and now it should work.

Let me know if it works for your formats now :)

Best regards

**Comment by BiponDas2** [comment]
Hi @rafaelpadilla Sir,
Much appreciated for your kind reply. I will let you know if it works.

Best regards.
