### ISSUE TITLE
"no file was found in the selected detection format in the annotations directory" while trying to show detection statistics

### ISSUE THREAD

**Issue by Siraj-Qazi** [rafaelpadilla/review_object_detection_metrics#43]
Hi.
I've been trying to find the mAP score for my dataset using this tool, but it can't find the detection annotations. I'm following the format specified:
`<class_name> <confidence> <left> <top> <right> <bottom>`

![image](https://user-images.githubusercontent.com/43324333/116795292-5da50900-aaed-11eb-9529-37d575f350ca.png)

My Dataset has two classes, 'person' and 'vehicle' and I've listed them in the aider-classes.txt as per VOC format.

Here is a sample file in my detections annotation directory:
```
person 0.9996482 224 69 248 116 
person 0.9983903 212 160 231 202 
person 0.7466929 241 89 252 117 
vehicle 0.9925392 103 133 163 236 
```

The environment setup is all as per the environment.yml file provided. It loads the ground truths correctly but fails to identify the detections annotations.

Could you please help me investigate this?

5.4.0-72-generic #80~18.04.1-Ubuntu

**Comment by rafaelpadilla** [comment]
Hi @Siraj-Qazi,

I tried to reproduce the error you are having, and noticed if your text files end with ' ', they will be considered invalid.

To prevent you to change all files, I changed the code. So, please, update it and let me know if that works now.

Attached to this message are the detection files I used to reproduce your error.
[Siraj-Qazi.zip](https://github.com/rafaelpadilla/review_object_detection_metrics/files/6410541/Siraj-Qazi.zip)

**Comment by Siraj-Qazi** [comment]
Hi Rafael,
Thank you for your reply. I couldn't find time to do it all day but I'm gonna quickly test it now and let you know :)

**Comment by Siraj-Qazi** [comment]
Hi @rafaelpadilla 
You were right! It was the issue with the ending `' '` after each line in my annotations file.
Your patch fixed it!
Thanks alot :)
