### ISSUE TITLE
Cann't show ground-truth statistics with coco annotation files

### ISSUE THREAD

**Issue by sunny123123** [rafaelpadilla/review_object_detection_metrics#45]
Can't not choose coco annotation file, because coco annotations just one file. Your tool just can choose a directory.
![image](https://user-images.githubusercontent.com/10163641/117796157-6336e780-b281-11eb-8a7a-752f287100e2.png)

what's wrong with my operations?

**Comment by rafaelpadilla** [comment]
Hi@sunny123123,

Thank you for your message.

The option selects a directory, because if other options are selected, such as PASCAL for example, you are expected to select multiple files.

Please, put your COCO .json file in a directory containing only the .json file.

**Comment by sunny123123** [comment]
oh, thanks for you reply quickly. You solved my problem.
Thanks
