### ISSUE TITLE
Unrecognized selector sent to instance 0x7f8f8579a940 on Mac

### ISSUE THREAD

**Issue by Harry-675** [rafaelpadilla/review_object_detection_metrics#49]
Hi
I found no result output after pressing the "run" button.
In the terminal it outputs "[QNSApplication macMinorVersion]: unrecognized selector sent to instance 0x7f8f8579a940" .
I' m running this application on Mac os. 
Hope get your help, thanks!

**Comment by rafaelpadilla** [comment]
Hi @Harry-675 ,

In a quick google search, it is related to libraries such as matplotlib and pyqt. 

Have you tried installing the requirements.txt in an anaconda environment?

**Comment by Harry-675** [comment]
> Hi @Harry-675 ,
> 
> In a quick google search, it seems this is related to libraries such as matplotlib and pyqt.
> 
> Have you tried installing the requirements.txt in an anaconda environment?

Yes, I have install the required environment according to environment.yml. I also found it's related to matplotlib and tried some solutions , but none of them worked. 

I tried in the linux also, everything works fine, so I think it's a mac problem.

Thanks for your reply, Thanks for your wonderful job!

**Comment by rafaelpadilla** [comment]
> > Hi @Harry-675 ,
> > In a quick google search, it seems this is related to libraries such as matplotlib and pyqt.
> > Have you tried installing the requirements.txt in an anaconda environment?
> 
> Yes, I have install the required environment according to environment.yml. I also found it's related to matplotlib and tried some solutions , but none of them worked.
> 
> I tried in the linux also, everything works fine, so I think it's a mac problem.
> 
> Thanks for your reply, Thanks for your wonderful job!

@Harry-675 ,

This is the first problem of this type reported in mac. Other users have successfully run this project on macs. As you are able to run it in another OS, I will flag this issue as "closed". But I kindly ask you to include here the solution if you can figure it out this problem on your mac.

Best regards
