### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by ozanpkr** [rafaelpadilla/review_object_detection_metrics#50]
Hi @rafaelpadilla . I used mmdetection toolbox for my project. After detection, I can get detection results in JSON format. But I couldn't use this file with your toolbox. How can I solve that? I  read the same issue but I don't know that how can I convert my son to your JSON format? You can reach my JSON with the help of the URL that followed;

https://drive.google.com/file/d/19zrA94O1CjP9H-ogkuy5Tid0XKDXFamx/view?usp=sharing

**Comment by rafaelpadilla** [comment]
Hi @ozanpkr ,

The current version does not support the mmdetection JSON format. I see that the format you provided me contains the detections. Do the ground-truth annotations follow the same format or your ground-truth format is different and is supported by the tool?

Anyway, to make it work, **you could write a converter to export your JSON file to any supported format** or **you could create a function to parse the JSON file**, so the tool can read your annotations.

If you want to take the second option, basically, your function needs to read the JSON file and return a list of [BoundingBox](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/684551117c96c4ec2f5ac78a35dab75ca8135a07/src/bounding_box.py#L8) objects. 

All parsing functions are in [converter.py](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/utils/converter.py). 

You can take a look at [coco2bb](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/utils/converter.py#L25) function, which parses a JSON file. If you modify `coco2bb` function with your own parser, you would just have to select the "COCO (.json)" option on the interface and it will work.

**Comment by ozanpkr** [comment]
Hi @rafaelpadilla ,

Firstly, the ground-truth annotations format is supported by the tool. You can reach my ground truth JSON with the help of the URL that followed;

https://drive.google.com/file/d/14Mc9IuMPj883T6vBkLLwZ1KOdOTEOJua/view?usp=sharing

Secondly, I will check coco2bb function after that I will let you know.

**Comment by rafaelpadilla** [comment]
@ozanpkr ,
Nice. Thanks.
