### ISSUE TITLE
It's much too Slow!

### ISSUE THREAD

**Issue by Harry-675** [rafaelpadilla/review_object_detection_metrics#52]
I tested it with 6500 images,  it works fine.
But when the number of images comes to more than ten thousnads, the program crash!

**Comment by rafaelpadilla** [comment]
Hi @Harry-675 ,

Please, could you inform which annotation formats you are using and the configuration of your machine?

I will try to replicate it and see what is happening.

Regards

**Comment by rafaelpadilla** [comment]
Closing issue as no update was reported

**Comment by hillvanwalker** [comment]
Hi, here I testd 10k images with 640x640 and its ground truth (yolo format), and detection of my yolov5 networks, format is (cls_id,conf,cx,cy,w,h)relative, it cost about 6 minute to show the result, very slow indeed, my cpu is i9-10900k.
