### ISSUE TITLE
More convenient Python usage

### ISSUE THREAD

**Issue by R-Peleg** [rafaelpadilla/review_object_detection_metrics#61]
Hi all, thank you for this great tool.

I am using the code here from Python (need to test and compare a model trained in various scenarios) and would like to see some improvements around the usage from code.
I can do the code changes around most of this but wanted to make sure it is welcome here in the current community, as they might change a lot of existing code.

The changes that jumped into mind:

- [ ] Renaming the main package name from `src` to some more useful name
- [ ] Publishing as a pip package
- [ ] Building a documentation site from sources
- [ ] Not opening a plotly window right on import (`from src.evaluators.coco_evaluator import get_coco_summary` makes a window to show)

Is there any interest besides me in such king of changes?

**Comment by rafaelpadilla** [comment]
Hi @R-Peleg ,

Thank you for your suggestion.

The package name `src` comes from the template used to create the structure of the project. So we do not think it is needed right now.

The creation of a pip package is indeed wanted. There is a discussion open for that.  I believe the site with the documentation from the docstrings should be made with the pip, right? 

Yeah, opening the plot window on the import is a bug and should be fixed.

If you would like to help us with any of these points, you are more than welcome to contribute.
