### ISSUE TITLE
No file was found for the selected detection format in the annotations directory

### ISSUE THREAD

**Issue by HnH19** [rafaelpadilla/review_object_detection_metrics#63]
I have all my .txt annotations in the directory file, with the correct format (the 1st one in the list), where does this error comes from then ?

**Comment by rafaelpadilla** [comment]
Hi @HnH19 

Please, could you specify what error message you are receiving?

Also, please, could you attach to your message a sample of a detection file and its associated ground-truth file?

Thanks

**Comment by HnH19** [comment]
Hi,

The error message if the following : 

%%
No File was found
No file was found for the selected detection format in the annotations directory.
%%
![ERROR](https://user-images.githubusercontent.com/84982134/126554648-91b8b6ea-4b3b-4eb2-8537-b25a292a254a.JPG)

Here are the annotations for a ground truth-detection pair.

By the way, there is nothing wrong with my ground truth upload, it is working.
The error occurs with the detection annotations file.

[ground_truth.txt](https://github.com/rafaelpadilla/review_object_detection_metrics/files/6858552/ground_truth.txt)
[detection.txt](https://github.com/rafaelpadilla/review_object_detection_metrics/files/6858553/detection.txt)

Thank you in advance.
HnH

**Comment by maketo97** [comment]
I meet the same problem as @HnH19. The format for ground truth and predictions is same also.

**Comment by ngunsu** [comment]
I have the same problem, but only in Linux. For some reason, in OSX the behavior is different

**Comment by rafaelpadilla** [comment]
Hi @HnH19,

I tried to replicate your problem, but no error was shown. See in the images below how I did with the files you provided

![image](https://user-images.githubusercontent.com/31217453/127069296-8626cad0-59dc-47e1-9ced-34c83447e6b5.png)

![image](https://user-images.githubusercontent.com/31217453/127067804-280fa38f-6315-42d4-8bfc-643315f70282.png)

![image](https://user-images.githubusercontent.com/31217453/127067787-d4090014-9548-4385-8324-59da50b78733.png)

Please, make sure you are following the steps below:

1) Put all your groundtruths .txt files in the same folder (ex: `groundtruths/`)
2) As your groundtruth bounding boxes are in relative formats (Yolo (.txt)), the images are required as the width and height of the images are needed to calculate the position of the bounding boxes. Thus, put all your images in the same folder (ex: `images/`)
3) Create a .txt file, where each line contains the name of your classes. Example: the first line (line 0) must have the name of the objects represented by class_id=0.
4) Put all your detections .txt files in the same folder. (ex: `detections\`) 

Make sure that the detections, images and groundtruth files of the same image are named the same. Example: Bounding box detections of image `/images/image_A.jpg` are represented by the file `/detections/image_A.txt`, and their groundtruth bounding boxes are in the file `/groundtruths/image_A.txt`.

Find in the file below an example I made with the files you provided. As I did not have your image, I created a dummy 100x100 black image.
[HnH19.zip](https://github.com/rafaelpadilla/review_object_detection_metrics/files/6881602/HnH19.zip)

Let me know if that works. :)

**Comment by rafaelpadilla** [comment]
@maketo97 , please, see the answer above and check if you are doing all steps correctly.

Let me know if that works now ;)

**Comment by tylertroy** [comment]
Hi @rafaelpadilla, I was seeing the same error. However, when I use your provided data in `HnH19.zip` and follow the above just as you describe the error no longer appears _but_ the output metrics are all 0. Any thoughts?

```
COCO METRICS:
AP: 0.0
AP50: 0.0
AP75: 0.0
APsmall: nan
APmedium: 0.0
APlarge: nan
AR1: 0.0
AR10: 0.0
AR100: 0.0
ARsmall: nan
ARmedium: 0.0
ARlarge: nan

PASCAL METRIC (AP per class)
person: 0

PASCAL METRIC (mAP)
mAP: 0.0
```

**Comment by rafaelpadilla** [comment]
Hi @tylertroy ,

Thank you for your message. I attached the file with a small change, and that's why the results are all 0. See the explanation: 

It is because the groundtruth file img_A.txt reports one object of class "person" (0)
`0 0.573211 0.407236 0.347754 0.628942`

and the detection img_A.txt reports a detection of object class "dog" (1)
`1 0.92 0.566021 0.417603 0.544014 0.666667`

Even though the IOU is high, the class of the detected object is different than the groundtruth object. So, the results must be indeed 0.

If you change the class of one of the files, you will see that the results will change :). Just change the ground-truth file img_A.txt to:
`1 0.573211 0.407236 0.347754 0.628942` 

and it will work.

Best regards

**Comment by rafaelpadilla** [comment]
Closing issue as no update was reported

**Comment by tylertroy** [comment]
Apologies @rafaelpadilla . Worked as suggestd
