### ISSUE TITLE
Calculate mAP with a different annotation format?

### ISSUE THREAD

**Issue by YashRunwal** [rafaelpadilla/review_object_detection_metrics#65]
Hello,

I am training a custom model based on CenterNet. To start with, I am training for 20 Epochs. I want the model to evaluate the mAP of the validation dataset after 10 epochs. Therefore, I want to use this repo. 

However, my dataset annotation format looks like this: x1, y1, x2, y2, class_id
It is not like YOLO Dataset and COCO Dataset. Every image has its own annotation file (.txt) with N bounding boxes.
The model evaluation returns the following: Top 100 box predictions, Top 100 scores, Top 100 class indices.

How do I in this case use this repo? I mean I can change the code too if needed. 

Thanks.

**Comment by rafaelpadilla** [comment]
Hi @YashRunwal ,

Yes, you could adapt the code to retrieve the mAP result after any epoch.

You have to call [get_pascalvoc_metrics](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/evaluators/pascal_voc_evaluator.py#L82) function passing a BoundingBox object representing your groundtruths (`gt_boxes`) and a BoundingBox object representing your detections (`det_boxes`).

See [here](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/49a614a6ca59e39f2aecd085730cc2e4d30cd886/src/bounding_box.py#L8) the BoundingBox class.

Follow [this](https://github.com/rafaelpadilla/Object-Detection-Metrics/tree/master/samples/sample_1) example to create your BoundingBox objects.

I hope that helps.

Best regards

**Comment by rafaelpadilla** [comment]
Closing issue as no update was reported
