### ISSUE TITLE
Packaging as pip modules

### ISSUE THREAD

**Issue by SJBertram** [rafaelpadilla/review_object_detection_metrics#7]
As per rafaelpadilla/Object-Detection-Metrics#58, it would be great if this could be published as a pip module on PyPi so that people had a consistent, reliable, trustworthy way to generate metrics for their object detection results. It looks like it is already mostly compatible as there is a skeleton `setup.py`, so hopefully it isn't too difficult. I don't know what restructuring may be required to avoid naming collisions with other packages.

While the repo is now called "review_object_detection_metrics", I think `import object_detection_metrics` is still a sensible name for the package.

I don't know whether @andreydung or @malpunek would still be interested in helping with this new version.

**Comment by rafaelpadilla** [comment]
@SJBertram that's a good idea. 

Some points we need to be aware:
* The current repository just came out of the oven, so people are still trying it. So, possible bugs and suggestions by the users might appear. Wouldnt it be better if we wait a little more before releasing it as a pip package? 
* As this project is part of an academic project, I would need to include an "About" screen.
* We would need to choose a license, so people can use it without any concerns.

What are your suggestions?

Regarding the other repository, I will answer it on the issue [https://github.com/rafaelpadilla/Object-Detection-Metrics/issues/58](https://github.com/rafaelpadilla/Object-Detection-Metrics/issues/58)

**Comment by potipot** [comment]
This code is great, much cleaner and understandable than the original COCOMetric. I like simple API plug-in of 
```python
def get_coco_summary(groundtruth_bbs, detected_bbs):
[...]
```
The IceVision library could definitely use it. Did you run some efficiency comparison with the original metric? How much faster/slower is this lib?

**Comment by rafaelpadilla** [comment]
> This code is great, much cleaner and understandable than the original COCOMetric. I like simple API plug-in of
> 
> ```python
> def get_coco_summary(groundtruth_bbs, detected_bbs):
> [...]
> ```
> 
> The [IceVision](https://github.com/airctic/icevision) library could definitely use it. Did you run some efficiency comparison with the original metric? How much faster/slower is this lib?

Please, leave this issue to be discussed with its original purpose. I kindly ask you to open another new issue including your comments.

**Comment by pwoolvett** [comment]
@rafaelpadilla I'd be glad to help you with the packaging process

* you could enable [discussions](https://docs.github.com/en/discussions/quickstart), or even a chat (eg discord) channel, to be transparent with respect to the direction /releases / fetures of the project.

With respect to the version/releas on pypi, common consensus is to use [semver](https://semver.org/) and keep the major below 1, eg `0.x.y`. This way, we have the best of both worlds

I can help setting up testing/release/pub for the project, but we need to discuss the details before...

**Comment by SJBertram** [comment]
I've never released on PyPi, but my understanding is that having the `setup.py` already gets you a step closer than the previous project.

With regards license, you've already got a [MIT-like license](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/LICENSE) so people are free to use it as long as they accept the terms. Although as it's modified then I don't think it's technically Open Source Compliant and compatible with other licenses. A plain MIT would allow anyone to use it without legal departments having to check and approve the license terms.

Looking at your additional clauses (I am not a lawyer, but) I think:
 * Number 2 is pretty much covered in the line "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software". 
   * It doesn't force people to specifically link back to this repo, but it does require credit and copyright notices.
   * Copyright notices are more flexible anyway. For example, what if the primary version of this software moved to another account (maybe you create a GitHub Organisation for your team/department/institution) or even another service? Your license would then be mandating people link to the wrong place.
 * Similarly, number 1 is covered by a combination of software license and academic convention. If other researchers don't publish their source code then the license terms of MIT won't force them to credit you in their paper (because the copyright only extends to the source code, not its outputs). But you've already got the citation request with details at the top of the README.
   * I don't know of _any_ license that requires acknowledgement of having used a tool when what you're publishing is a paper based on its outputs. It would be odd even for a proprietary app.
   * Also, definitions in licenses are hard. What is an "academic publication"? Is a company publishing a paper at a conference an "academic paper", or is it only "academic" if it comes from academia?
   * Related to that, what if they're not using Latex? Your license could currently be interpreted to mandate the use of Bibtex, but if you're not using Latex then that's not useful. Yet if they _don't_ use Bibtex then they're in breach of your license.


I like the idea of keeping versions below 1.0 to start with so that people know it is potentially unstable and prone to API change, while still allowing them to try it out if they want to.

**Comment by rafaelpadilla** [comment]
Hi @SJBertram ,

Thank you for your clear response :)

Regarding the number 2. I think this is not a problem, once I do not intend to move this repository to any other account. And it does not matter if the tool points to a non existing repository. The user will still be able to use the tool even if the repository name is changed, right?

In the next point, you mentioned that "the license terms of MIT won't force them to credit you in their paper (because the copyright only extends to the source code, not its outputs)" is clear. I believe in the academic world, there is no legal way to "force" someone to make reference to your work. But I believe that researchers using this tool have no reason not to cite it in their publications. To reinforce it, I added a splash screen that pops up when the user opens the tool asking the users to make reference to it. The reason for the citations is that this tool is part of a project that received financial aids. And one way the funding institution evaluates the success of the financial aid is by tracking the amount of citations.

To avoid misinterpretations of the license, I removed the Latex format, and changed it a little bit.

@pwoolvett, I opened the discussion tab. We could continue this conversation there. As you are more experienced in creating the pip package. Please, let me know what the required steps are.
