### ISSUE TITLE
How to calculate precision for small, medium and large objects?

### ISSUE THREAD

**Issue by RicRicci22** [rafaelpadilla/review_object_detection_metrics#70]
Hi,
I am trying to calculate the precision of an algorithm on small medium and large objects.
For instance I pose constraints on the area,
area<150 ----- small
area>500 ----- large
150<area<500 ----- medium

How can I calculate the precision for these type of objects? Because I am confused by the fact that the predictions can have different size, but referring to the same true objects, depending on how good is the detector.
In this case, how can I know that a predicted bounding box was meant to detect a small, a medium or a large object??
I am so confused by this...

Thank you!

**Comment by rafaelpadilla** [comment]
Hi @RicRicci22 ,

In the current version, those values are hardcoded. In a future version these values could be adapted.

In this version the default area thresholds here follows the values defined in COCO, that is,
small: area <= 32**2
medium: 32**2 <= area <= 96**2
large:  96**2 <= area.

You can adapt these values for your needs in the following parts of the code:
[small](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/evaluators/coco_evaluator.py#L106)
[medium](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/evaluators/coco_evaluator.py#L117)
[large](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/evaluators/coco_evaluator.py#L128)

Regards,
Rafael

**Comment by RicRicci22** [comment]
Hi @rafaelpadilla, thank you for your kind answer. 
And thank you for the repository! :)
