### ISSUE TITLE
Questions about APs, APm, APl

### ISSUE THREAD

**Issue by Zengyf-CVer** [rafaelpadilla/review_object_detection_metrics#71]
@rafaelpadilla 
I know the calculation formula of mAP, the sum of AP of all classes is divided by the number of all classes.
However, I am not quite clear about the calculation formulas of APs, APm and APl. The following is my analysis. Please see if it is correct.
Assume that the number of all categories is N, the number of small objects is Ns, the number of medium objects is Nm, and the number of large objects is Nl.
- Then N=Ns+Nm+Nl
- APs is equal to the sum of APs of all small objects divided by Ns.
- APm is equal to the sum of AP of all medium objects divided by Nm.
- APl is equal to the sum of AP of all large objects divided by Nl.
#### Is my analysis correct?

**Comment by rafaelpadilla** [comment]
Hi @Zengyf-CVer ,

AP regarding the sizes of the bounding boxes (small, medium and large) is computed as the mean of the APs considering objects of a specific size. So, I believe you are right.

Please, check [here](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/evaluators/coco_evaluator.py#L109) for more details.

**Comment by Zengyf-CVer** [comment]
@rafaelpadilla 
Thank you very much. After reading your code, I already know how to calculate it.
