### ISSUE TITLE
How to run in terminal?

### ISSUE THREAD

**Issue by Harry-675** [rafaelpadilla/review_object_detection_metrics#82]
How to run without ui? As ui is not convenient in the remote server.

**Comment by RohitKeshari** [comment]
Anyone able to run this in terminal?

**Comment by philippe-heitzmann** [comment]
Could team please provide docs on how to run this in command line? Any pointers on this would be much appreciated as not all users will want to use the GUI. Thank you

**Comment by rafaelpadilla** [comment]
Hi guys,

Our [previous tool](https://github.com/rafaelpadilla/Object-Detection-Metrics), which has limited bounding box formats, allows calls from command line.

So far, the current tool does not have support to run it via terminal.

Some members of the community have started some actions on implementing such function, but nothing has been evolved. 

If anyone would like to contribute with such important functionality, we really appreciate it :pray: 

We all expect a similar command line interface as [here](https://github.com/rafaelpadilla/Object-Detection-Metrics#optional-arguments).

I was thinking of a script `src/cli/evaluation.py` with the following arguments representing the [numbered fields of the visual interface](https://github.com/rafaelpadilla/review_object_detection_metrics/raw/main/data/images/printshot_main_screen.png):

`--gt_annotations`: representing field "1"
`--gt_images`: representing field "2"
`--gt_classes`: representing field "3"
`--gt_format`: representing field "4"
`--det_annotations`: representing field "6"
`--det_classes`: representing field "7"
`--det_format`: representing field "8"
`--metrics`: list of metrics as represented by field "10"
`--pascal_iou_thresh`: PASCAL VOC threshold (default 0.5)
`--output_path`: representing field "11"
