### ISSUE TITLE
no file was found in the selected detection format in the annotations directory - for detections only

### ISSUE THREAD

**Issue by apecundo** [rafaelpadilla/review_object_detection_metrics#85]
Hi Rafael, 

Good day! I have tried testing this on my dataset, and ground truth detection works fine. 

However, for the detection files, following the format prescribed, I am getting an error saying that "no file was found in the selected detection format..".

I have tried double checking the other previous issues related to this as well but I am still stuck getting this error.  I have tried double checking the format and it seems to be aligned with the prescription. 

May I request for your help understanding if I have missed anything else required for the file preparation?

For your reference, I am using the detection format of <class name> <confidence> <left> <top> <width> <height>

[detections_allan.zip](https://github.com/rafaelpadilla/review_object_detection_metrics/files/7492039/detections_allan.zip)

Thank you so much for this!

Regards
Allan

**Comment by AMF2601** [comment]
Same error when testing for YOLOv5 format

**Comment by AMF2601** [comment]
> Same error when testing for YOLOv5 format

Solved it. It was due to the complex file name of the label and image file. Rename the images and labels to a simple format. Ex: 1.jpg and 1.txt. The confidence score can be added to the label file by running detect.py --save-txt --save-conf.

**Comment by XiangqingZhang** [comment]
Same errors occurred. please help me??
[metrics_visualization.zip](https://github.com/rafaelpadilla/review_object_detection_metrics/files/7780435/metrics_visualization.zip)
