### ISSUE TITLE
Unable to type or click file path

### ISSUE THREAD

**Issue by millyleadley** [rafaelpadilla/review_object_detection_metrics#88]
Have set up using the instructions in the readme (ie. created the environment with `environment.yml`, activated the env, ran the install command) but when I run I'm unable to type any file paths in the GUI or select any files through finder (as pictured). Any ideas on whats wrong?

<img width="668" alt="Screenshot 2021-12-13 at 12 54 43" src="https://user-images.githubusercontent.com/32493490/145816322-230aaaef-7db7-4238-b7ea-ac83da6b9be5.png">
<img width="812" alt="Screenshot 2021-12-13 at 12 55 30" src="https://user-images.githubusercontent.com/32493490/145816326-45aa0476-7642-4abc-aee4-2567231603c4.png">

**Comment by manuelrames** [comment]
Hello, I am having the same problem as @millyleadley. Were you able to fix the issue by any chance? Thanks you in advance!

**Comment by curiosity654** [comment]
Same trouble here
