### ISSUE TITLE
Zero scores

### ISSUE THREAD

**Issue by alsheabi** [rafaelpadilla/review_object_detection_metrics#91]
I used gt and dt files with IoU 0.5 in both of [https://github.com/rafaelpadilla/Object-Detection-Metrics](url) and [https://github.com/Cartucho/mAP](url) with getting mAP 97%, but when I used this repo I get Zero !!!

GT files (Abs .txt):
class_name xyx2y2
DR files (Abs .txt):
class_name Confidence xyx2y2

When I set IoU 0.1 get score 10%

Result using this Repo:

![iou](https://user-images.githubusercontent.com/6864735/150706216-bb70b64c-2baf-4c1c-bcf2-f8203f9286e9.png)

Result using @rafaelpadilla  rafaelpadilla [https://github.com/rafaelpadilla/Object-Detection-Metrics](url)

![iou1](https://user-images.githubusercontent.com/6864735/150706564-0e8d1ab7-6b4a-4e8e-9d0f-4c87dfad1529.png)

**Comment by ooobelix** [comment]
Hi @alsheabi, is it the same behaviour as https://github.com/rafaelpadilla/review_object_detection_metrics/issues/68 ?

**Comment by alsheabi** [comment]
> Hi @alsheabi, is it the same behaviour as #68 ?

@ooobelix  Hi, I think it's different because when I set Threshold IoU <0.1, I get accuracy!
