### ISSUE TITLE
zero values

### ISSUE THREAD

**Issue by serenadimaggio** [rafaelpadilla/review_object_detection_metrics#94]
Hi,
I have a problem regarding metrics' values, because they are all zero and I can't understand why!
I'm using the zip repository that I attach here, where the ground truth box and the detection box have an IoU of 0.75.
My gt annotations are in absolute values, while my dt annotation is  left, top, right, bottom.
What is my error?

[ten.zip](https://github.com/rafaelpadilla/review_object_detection_metrics/files/8190731/ten.zip)

**Comment by gonewiththewind1939** [comment]
Have you solved this issue? because I have meet a similar issue.
