### ISSUE TITLE
Detection Annotations 

### ISSUE THREAD

**Issue by rafcy** [rafaelpadilla/review_object_detection_metrics#99]
Hello,
I am trying to use the application but it cannot read my detection annotations. Upon testing several scenarios I found out that the issue is because I choose <class name> <confidence> <left> <top>< right > <bottom > (ABSOLUTE)  format but having float for the bounding box points. The issue though is fixed ONLY if I change the <right> value into an integer, if I change any other value to an integer it cannot read the whole file.

formats that work:
`car 0.6775752902030945 395.8804626464844 256.385498046875 416.0 282.61138916015625`
`car 0.6775752902030945 395.8804626464844 256.385498046875 416 282.61138916015625`

formats that don't work:
`car 0.6775752902030945 395.8804626464844 256.385498046875 416.1230 282.61138916015625`
`car 0.6775752902030945 395.8804626464844 256.385498046875 416.1230 282.0`
`car 0.6775752902030945 395.8804626464844 256 416.1230 282.61138916015625`
`car 0.6775752902030945 395 256 416.1230 282.61138916015625`

I looked up the source code (bounding boxes class) and it gets the x,y,x2,y2 values and then converts into float so it shouldn't be an issue so I assume the issue is somewhere I haven't checked yet.
I am sending you also a sample of my files, ground truth are in Yolo format and the detections are in <class name> <confidence> <left> <top>< right > <bottom > (ABSOLUTE) (also don't know if this diversity of the annotations causes the error as well)
Thank you in advance
[sample_evalv.zip](https://github.com/rafaelpadilla/review_object_detection_metrics/files/8222887/sample_evalv.zip)

**Comment by rafcy** [comment]
After a bit of research in the source code, I found out about this line https://github.com/rafaelpadilla/review_object_detection_metrics/blob/56d8969739d4774b4bab5b8122870e7e4c833021/src/utils/validations.py#L482 .
It checks if the float value is the same as the integer value. I removed the check and everything works fine, for my case at least.

**Comment by rafaelpadilla** [comment]
@rafcy ,

It's because the absolute bounding box values should be integers only. Make your formats as these toy examples:

[Absolute XYX2Y2](https://github.com/rafaelpadilla/review_object_detection_metrics/tree/main/toyexample/dets_classid_abs_xyx2y2) 
[Absolute XYWH](https://github.com/rafaelpadilla/review_object_detection_metrics/tree/main/toyexample/dets_classid_abs_xywh)
